[tool.poetry]
name = "nonebot"
version = "2.0.0"
description = "An asynchronous python bot framework."
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://docs.nonebot.dev/"
repository = "https://github.com/nonebot/nonebot"
documentation = "https://docs.nonebot.dev/"
keywords = ["bot", "qq", "qqbot", "mirai", "coolq"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
include = ["nonebot/py.typed"]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.13.3"
pygtrie = "^2.3.3"
fastapi = "^0.58.1"
uvicorn = "^0.11.5"
pydantic = { extras = ["dotenv"], version = "^1.6.1" }
apscheduler = { version = "^3.6.3", optional = true }
# nonebot-test = { version = "^0.1.0", optional = true }

loguru = "^0.5.1"
[tool.poetry.dev-dependencies]
yapf = "^0.30.0"
sphinx = "^3.1.1"
sphinx-markdown-builder = { git = "https://github.com/nonebot/sphinx-markdown-builder.git" }

[tool.poetry.extras]
# test = ["nonebot-test"]
scheduler = ["apscheduler"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
