name: 'NoneBot2 Publish Bot'

on:
  push:
    branches:
      - master
  issues:
    types: [opened, reopened, edited]
  pull_request:
    types: [closed]

jobs:
  publish_bot:
    runs-on: ubuntu-latest
    name: nonebot2 publish bot
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: NoneBot2 Publish Bot
        uses: nonebot/nonebot2-publish-bot@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: master
          plugin_path: docs/.vuepress/public/plugins.json
          bot_path: docs/.vuepress/public/bots.json
          adapter_path: docs/.vuepress/public/adapters.json
