name: Release Nonebot Plugin Docs

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: "x64"

      - uses: Gr1N/setup-poetry@v4

      - name: Build Docs
        run: |
          yarn install
          yarn build:plugin --out-dir ./packages/nonebot-plugin-docs/nonebot_plugin_docs/dist

      - name: Publish Package
        run: |
          cd packages/nonebot-plugin-docs/
          poetry version $(poetry version -s)
          poetry build
          poetry publish -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.PYPI_PASSWORD}}
