name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Build API Doc
        uses: ./.github/actions/build-api-doc

      - name: Archive Files
        run: yarn archive $(poetry version -s)

      - name: Push Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m ":bookmark: Release $(poetry version -s)"
          git tag v$(poetry version -s)
          git push && git push --tags
