name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: "x64"

      - uses: Gr1N/setup-poetry@v4

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set up dependencies
        run: |
          poetry install -E all

      - name: Build Doc
        run: poetry run sphinx-build -M markdown ./docs_build ./build

      - name: Copy Files
        run: cp -r ./build/markdown/* ./website/docs/api/

      - name: Archive Files
        run: yarn archive $(poetry version -s)

      - name: Push Tag and Release to PyPI
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m ":bookmark: Release $(poetry version -s)"
          git tag v$(poetry version -s)
          git push --tags
          poetry build
          poetry publish -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.PYPI_PASSWORD}}
